
version: '3.8'

services:
  php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000
    depends_on:
      - mysql_container

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/BookingTrackerApi/public/:/app/apps/BookingTrackerApi/public
    depends_on:
      - php_container

  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWD}
    ports:
      - 3306:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./var/MySQL:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_container
    restart: always
    links:
      - mysql_container
    ports:
      - 8006:80
    environment:
      - PMA_HOST=mysql_container
      - PMA_PORT=${DATABASE_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${DATABASE_ROOT_PASSWD}
    depends_on:
        - mysql_container
